# Generated by: toolbox make-shell gopass cfssl
let
  pkgs = import <nixpkgs> {};
  toolboxSrc = builtins.fromJSON (builtins.readFile ./toolbox.json);
  toolbox = import (pkgs.fetchFromGitHub {
    owner = "Caascad";
    repo = "toolbox";
    rev = toolboxSrc.commit;
    sha256 = toolboxSrc.sha256;
  }) {};
in
  pkgs.runCommand "deps" {
    buildInputs = with toolbox; [
      gopass cfssl
    ];
  } ""
